# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "nct6775" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c8d30941-bcf4-45d2-96c1-407f9c7cdb29";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E8BA-C9A5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Add your external drives here

  environment.systemPackages = [
    pkgs.ntfs3g
  ];

  fileSystems."/run/media/mgkallits/nvme" =
    { device = "/dev/disk/by-uuid/6674ACA074AC7489";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" ];
    };

  # fileSystems."/mnt/windows" =
  #   { device = "/dev/disk/by-uuid/4CFAFB64FAFB492A"; # UUID of nvme1n1p3
  #     fsType = "ntfs-3g"; # Replace with the correct filesystem type
  #     options = [ "rw" "uid=1000" ]; # Adjust options as needed
  #   };

  fileSystems."/run/media/mgkallits/hdd1" =
    { device = "/dev/disk/by-uuid/2E440EC8440E92AF";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000" ];
    };


  fileSystems."/run/media/mgkallits/hdd2" =
    { device = "/dev/disk/by-uuid/9A049845049825F3";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" ];
    };

  # swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

